# Generated by Django 4.2.13 on 2024-05-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='bussinesses',
        ),
    ]
