# Generated by Django 4.2.13 on 2024-05-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_users_user_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
